### PR TITLE
Added the ERD screenshot

### PR DESCRIPTION
**Pull request by queeksm**
Added the ERD screenshot and we are ready to merge to development.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required 
### Hello team :wave: 
Great work on the ER diagram :clap: 

Let's address some issues.
**[REQUIRED]**
* User table has an `image_link` field. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png)  from  Pathwright).

**Reading Suggestion for Likes feature Implementation.**
* I like the fact that we will implement like for both posts and comments. To implement that, we can use only one Like table and then make use of [Polymorphic Associations](https://dev.to/adjoa/rails-polymorphic-associations-511n) to achieve the functionality. Read more about [Single-table inheritance vs. polymorphic associations](https://www.freecodecamp.org/news/single-table-inheritance-vs-polymorphic-associations-in-rails-af3a07a204f2/) to get better understanding on how to implement the feature.

**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by Anna-Myzukina** [comment]
## Hi @queeksm !   :wave: 

* [ ] ERD diagram should be similar to : 
-------------------------------------------------------------------------------------------------------------------------------
bd

* [ ] Note that ID ONLY for friendships is optional!
* [ ] Please assign correctly the Primary Keys (PK) and Foreign Keys (FK).





### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by queeksm** [comment]
Regarding the changes to the ERD according to the last review.
We never included a "Notification entity" within our ERD, this led us to think that the review was aimed to a different team, however, we refactored some primary and foreign keys to ease on the reading and to simplify the relationships between the tables.

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

Thank you for applying the suggested changes.
You can merging now and move forward :smile: 

Good continuation :handshake: 

Mael FOSSO

**Pull request merged**
